$('body')
    .append(
        $('<h1>')
            .text('Todo List')
    )
    .append(
        $('<input>')
            .attr('placeholder','Enter Task')
            .attr('id','newTask')
    )
    .append(
        $('<button>')
            .text('Add Task')
            .attr('id','btn')
            .click(()=>{
                $('#taskList')
                    .append(
                        $('<li>')
                            .text(
                                $('#newTask').val()
                            )
                            .append(
                                $('<button>')
                                    .attr('class','up')
                                    .text('⬆️')
                                    .click((ev)=>{
                                        $(ev.target)
                                            .parent()
                                            .insertBefore(
                                                $(ev.target).parent().prev()
                                            )
                                    })
                            )
                            .append(
                                $('<button>')
                                    .attr('class','down')
                                    .text('⬇️')
                                    .click((ev)=>{
                                        $(ev.target)
                                            .parent()
                                            .insertAfter(
                                                $(ev.target).parent().next()
                                            )
                                    })
                            )
                            .append(
                                $('<button>')
                                    .attr('class','delete')
                                    .text('❌')
                                    .click((ev)=>{
                                        $(ev.target)
                                            .parent()
                                            .remove()
                                    })
                            )
                    )
            })
    )
    .append(
        $('<ul>')
            .attr('id','taskList')
    )